apiVersion: apps/v1
kind: Deployment
metadata:
  name: rails-on-k8s-deployment
  labels:
    app: rails-on-k8s
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rails-on-k8s
  template:
    metadata:
      labels:
        app: rails-on-k8s
    spec:
      terminationGracePeriodSeconds: 1
      containers:
        - name: rails-on-k8s
          image: truvazia/rails_on_k8s:0.2-slim
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: RAILS_ENV
              value: production
            - name: RAILSONK8S_DATABASE_NAME
              value: railsonk8s
            - name: RAILSONK8S_DATABASE_USERNAME
              value: postgres
            - name: RAILSONK8S_DATABASE_HOST
              valueFrom:
                secretKeyRef:
                  name: railsonk8s-db
                  key: railsonk8s-database-host
            - name: RAILSONK8S_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: railsonk8s-db
                  key: railsonk8s-database-password
